---
- name: MariaDB
  hosts: centos
  gather_facts: true
  become: true
  tasks:
    - name: install
      yum:
        name:
          - MariaDB-server
          - MariaDB-client
          - python3-pymysql
        state: latest
    
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started