# This playbook joins a windows system to a domain
---
- name: Join windows machine to a domain
  hosts: workstations
  gather_facts: no
  vars_prompt:
  - name: domainuser
    prompt: "Please enter the username of a domain user"
    private: no
  
  - name: domainpass
    prompt: "Please enter the password of the domain user"
    private: yes

  tasks:
  - win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ hostname }}"
      domain_admin_user: "{{ domainuser }}"
      domain_admin_password: "{{ domainpass }}"
      domain_ou_path: "OU=Workstations,OU=Computers,OU=blue11,DC=blue11,DC=local"
      state: domain
    register: domain_state
    
  - win_reboot:
    when: domain_state.reboot_required