# This playbook creates smb file shares
---
- name: File share creation
  hosts: 10.0.5.6
  gather_facts: no

  tasks:
  - name: Install file server

  - name: read groups

  - name: create share directory

  - name: create group directories

  - name: create smb shares