# This playbook initializes and configures domain related utlities for windows server
---
- name: Create a blue11 domain controller
  hosts: 10.0.5.5
  gather_facts: no
  vars_prompt:
  - name: adminpassword
    prompt: "Please enter a safe mode password"
    private: yes

  tasks:
    - name: Create new forest
      win_domain:
          dns_domain_name: "{{ domain }}"
          safe_mode_password: "{{ adminpassword }}"
      register: domain_install

    - name: Reboot after creation
      when: domain_install.reboot_required
      win_reboot:
        msg: "Server config in process; rebooting..."
        test_command: 'exit (Get-Service -Name DNS).Status -ne "running"'

    - name: DNS Config
      win_shell:
          Add-DnsServerForwarder -IPAddress "{{ gateway }}" -PassThru