# This playbook configures windows machiens to use a static IP

- name: windows-networking
  hosts: 10.0.5.6
  gather_facts: no
  vars_prompt:
  - name: adminpassword
    prompt: "Please enter a password for the local Administrator"
    private: yes

  tasks:
  - name: Set the local Administrator
    win_user:
      name: Administrator
      password: "{{ adminpassword }}"
      state: present
      password_never_expires: yes
  
  - name: Change Time Zone
    win_timezone:
        timezone: Eastern Standard Time
    register: timezone

  - name: Change hostname
    win_hostname:
      name: "{{ hostname }}"

  - name: Create a deploy directory
    win_file:
      path: C:\480
      state: directory
  
  - name: Load dhcp-to-static j2 file
    win_template:
      src: files/windows/dhcp-to-static.ps1.j2
      dest: C:\480\dhcp-to-static.ps1

  - name: Run dhcp-to-static script
    async: 10
    poll: 0
    win_shell:
      C:\480\dhcp-to-static.ps1