# This playbook enables RDP & High-Performance power profule
---
- name: RDP and Profile Update
  hosts: workstations
  gather_facts: no

  tasks:
  - name: Enable Remote Desktop
    win_shell:
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
  
  - name: Enable RDP Firewall Fule
    win_shell:
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

  - name: Change power plan to high performance
    win_power_plan:
      name: high performance