windows:
  hosts:
  children:
    servers:
      hosts:
        10.0.5.5:
          hostname: dc-blue11
        10.0.5.6:
          hostname: fs01
    workstations:
      hosts:
        10.0.5.89:
          hostname: wks1
        10.0.5.90:
          hostname: wks2

  vars:
    ansible_user: deployer
    device: Ethernet0
    netmask: 255.255.255.0
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue11.local
    ansible_shell_type: powershell